### ISSUE TITLE
Allow Basic Auth

### ISSUE THREAD

**Issue by KristofKlein** [akoniecki/AL-Go-OnPremise-Deployer#3]
Hi,

nice project, I will have an eye on this one. However, it looks like your "OnPrem" is an AAD driven solution. I think this is a fair assumption, but not thought wide enough for what onPrem people are "used to do". 

Kind of a nice idea to piggyback the authContext with additional context...maybe here you could also onboard a user/pswd[apiKey] and allows this as some sort of fallback/alternative.

**Comment by akoniecki** [comment]
Hi Kristof,

I agree that the solution in current form is aimed to support Entra ID driven implementations.

But! Basic Auth implementation is technically possible, at least from the AL-Go/BCContainerHelper code perspective. I will definitely do some testing on it.

Thanks for sharing your insight and idea! I will keep you posted.

**Comment by KristofKlein** [comment]
well, I can at least tell you, that I it change a bit locally and in fact it does work ;)

**Comment by akoniecki** [comment]
@KristofKlein, would you consider contributing?
